package com.alumni.model.entities;
// Generated 2 avr. 2013 10:45:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private int idetudiant;
     private Integer idpromotion;
     private int idcompte;
     private Integer idposte;
     private String genre;
     private Date datedenaissance;
     private String nom;
     private String prenom;
     private String adresse;
     private String mail;
     private String tel;
     private String photoprofil;
     private String cv;

    public Etudiant() {
    }

	
    public Etudiant(int idetudiant, int idcompte, String nom, String prenom, String adresse, String mail) {
        this.idetudiant = idetudiant;
        this.idcompte = idcompte;
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.mail = mail;
    }
    public Etudiant(int idetudiant, Integer idpromotion, int idcompte, Integer idposte, String genre, Date datedenaissance, String nom, String prenom, String adresse, String mail, String tel, String photoprofil, String cv) {
       this.idetudiant = idetudiant;
       this.idpromotion = idpromotion;
       this.idcompte = idcompte;
       this.idposte = idposte;
       this.genre = genre;
       this.datedenaissance = datedenaissance;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.mail = mail;
       this.tel = tel;
       this.photoprofil = photoprofil;
       this.cv = cv;
    }
   
    public int getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }
    public Integer getIdpromotion() {
        return this.idpromotion;
    }
    
    public void setIdpromotion(Integer idpromotion) {
        this.idpromotion = idpromotion;
    }
    public int getIdcompte() {
        return this.idcompte;
    }
    
    public void setIdcompte(int idcompte) {
        this.idcompte = idcompte;
    }
    public Integer getIdposte() {
        return this.idposte;
    }
    
    public void setIdposte(Integer idposte) {
        this.idposte = idposte;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public Date getDatedenaissance() {
        return this.datedenaissance;
    }
    
    public void setDatedenaissance(Date datedenaissance) {
        this.datedenaissance = datedenaissance;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getPhotoprofil() {
        return this.photoprofil;
    }
    
    public void setPhotoprofil(String photoprofil) {
        this.photoprofil = photoprofil;
    }
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }




}


