package com.alumni.model.entities;
// Generated 31 mars 2013 21:31:29 by Hibernate Tools 3.2.1.GA



/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private int idetudiant;
     private int idpromotion;
     private int idcompte;
     private String nom;
     private String prenom;
     private String adresese;
     private String mail;
     private Integer tel;

    public Etudiant() {
    }

	
    public Etudiant(int idetudiant, int idpromotion, int idcompte, String nom, String prenom, String adresese, String mail) {
        this.idetudiant = idetudiant;
        this.idpromotion = idpromotion;
        this.idcompte = idcompte;
        this.nom = nom;
        this.prenom = prenom;
        this.adresese = adresese;
        this.mail = mail;
    }
    public Etudiant(int idetudiant, int idpromotion, int idcompte, String nom, String prenom, String adresese, String mail, Integer tel) {
       this.idetudiant = idetudiant;
       this.idpromotion = idpromotion;
       this.idcompte = idcompte;
       this.nom = nom;
       this.prenom = prenom;
       this.adresese = adresese;
       this.mail = mail;
       this.tel = tel;
    }
   
    public int getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }
    public int getIdpromotion() {
        return this.idpromotion;
    }
    
    public void setIdpromotion(int idpromotion) {
        this.idpromotion = idpromotion;
    }
    public int getIdcompte() {
        return this.idcompte;
    }
    
    public void setIdcompte(int idcompte) {
        this.idcompte = idcompte;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresese() {
        return this.adresese;
    }
    
    public void setAdresese(String adresese) {
        this.adresese = adresese;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }




}


