package com.alumni.model.entities;
// Generated 9 avr. 2013 15:10:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HistoriqueEtudiantPoste generated by hbm2java
 */
public class HistoriqueEtudiantPoste  implements java.io.Serializable {


     private HistoriqueEtudiantPosteId id;
     private Date datefin;

    public HistoriqueEtudiantPoste() {
    }

	
    public HistoriqueEtudiantPoste(HistoriqueEtudiantPosteId id) {
        this.id = id;
    }
    public HistoriqueEtudiantPoste(HistoriqueEtudiantPosteId id, Date datefin) {
       this.id = id;
       this.datefin = datefin;
    }
   
    public HistoriqueEtudiantPosteId getId() {
        return this.id;
    }
    
    public void setId(HistoriqueEtudiantPosteId id) {
        this.id = id;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }




}


