package com.alumni.model.entities;
// Generated 2 avr. 2013 10:45:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Promotion generated by hbm2java
 */
public class Promotion  implements java.io.Serializable {


     private int idpromotion;
     private Date annee;
     private String typepromo;

    public Promotion() {
    }

	
    public Promotion(int idpromotion, Date annee) {
        this.idpromotion = idpromotion;
        this.annee = annee;
    }
    public Promotion(int idpromotion, Date annee, String typepromo) {
       this.idpromotion = idpromotion;
       this.annee = annee;
       this.typepromo = typepromo;
    }
   
    public int getIdpromotion() {
        return this.idpromotion;
    }
    
    public void setIdpromotion(int idpromotion) {
        this.idpromotion = idpromotion;
    }
    public Date getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Date annee) {
        this.annee = annee;
    }
    public String getTypepromo() {
        return this.typepromo;
    }
    
    public void setTypepromo(String typepromo) {
        this.typepromo = typepromo;
    }




}


