package com.alumni.model.entities;
// Generated 9 avr. 2013 15:10:00 by Hibernate Tools 3.2.1.GA



/**
 * RelationEtudiant generated by hbm2java
 */
public class RelationEtudiant  implements java.io.Serializable {


     private RelationEtudiantId id;
     private String etat;

    public RelationEtudiant() {
    }

	
    public RelationEtudiant(RelationEtudiantId id) {
        this.id = id;
    }
    public RelationEtudiant(RelationEtudiantId id, String etat) {
       this.id = id;
       this.etat = etat;
    }
   
    public RelationEtudiantId getId() {
        return this.id;
    }
    
    public void setId(RelationEtudiantId id) {
        this.id = id;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


