package com.alumni.model.entities;
// Generated 2 avr. 2013 10:45:10 by Hibernate Tools 3.2.1.GA



/**
 * RelationEtudiantId generated by hbm2java
 */
public class RelationEtudiantId  implements java.io.Serializable {


     private int idetudiant1;
     private int idetudiant2;

    public RelationEtudiantId() {
    }

    public RelationEtudiantId(int idetudiant1, int idetudiant2) {
       this.idetudiant1 = idetudiant1;
       this.idetudiant2 = idetudiant2;
    }
   
    public int getIdetudiant1() {
        return this.idetudiant1;
    }
    
    public void setIdetudiant1(int idetudiant1) {
        this.idetudiant1 = idetudiant1;
    }
    public int getIdetudiant2() {
        return this.idetudiant2;
    }
    
    public void setIdetudiant2(int idetudiant2) {
        this.idetudiant2 = idetudiant2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelationEtudiantId) ) return false;
		 RelationEtudiantId castOther = ( RelationEtudiantId ) other; 
         
		 return (this.getIdetudiant1()==castOther.getIdetudiant1())
 && (this.getIdetudiant2()==castOther.getIdetudiant2());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdetudiant1();
         result = 37 * result + this.getIdetudiant2();
         return result;
   }   


}


