package com.alumni.model.entities;
// Generated 2 avr. 2013 10:45:10 by Hibernate Tools 3.2.1.GA



/**
 * RelationEtudiant generated by hbm2java
 */
public class RelationEtudiant  implements java.io.Serializable {


     private RelationEtudiantId id;

    public RelationEtudiant() {
    }

    public RelationEtudiant(RelationEtudiantId id) {
       this.id = id;
    }
   
    public RelationEtudiantId getId() {
        return this.id;
    }
    
    public void setId(RelationEtudiantId id) {
        this.id = id;
    }




}


