package com.alumni.model.entities;
// Generated 5 avr. 2013 18:13:24 by Hibernate Tools 3.2.1.GA



/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private int idinscrit;
     private int idcompte;
     private String numharpege;
     private String nom;
     private String prenom;
     private String adresse;
     private String mail;
     private Integer tel;

    public Responsable() {
    }

	
    public Responsable(int idinscrit, int idcompte) {
        this.idinscrit = idinscrit;
        this.idcompte = idcompte;
    }
    public Responsable(int idinscrit, int idcompte, String numharpege, String nom, String prenom, String adresse, String mail, Integer tel) {
       this.idinscrit = idinscrit;
       this.idcompte = idcompte;
       this.numharpege = numharpege;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.mail = mail;
       this.tel = tel;
    }
   
    public int getIdinscrit() {
        return this.idinscrit;
    }
    
    public void setIdinscrit(int idinscrit) {
        this.idinscrit = idinscrit;
    }
    public int getIdcompte() {
        return this.idcompte;
    }
    
    public void setIdcompte(int idcompte) {
        this.idcompte = idcompte;
    }
    public String getNumharpege() {
        return this.numharpege;
    }
    
    public void setNumharpege(String numharpege) {
        this.numharpege = numharpege;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }




}


