package com.alumni.model.entities;
// Generated 31 mars 2013 21:31:29 by Hibernate Tools 3.2.1.GA



/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private int idinscrit;
     private int idcompte;
     private Integer numharpege;
     private String nom;
     private String prenom;
     private String adresese;
     private String mail;
     private Integer tel;

    public Responsable() {
    }

	
    public Responsable(int idinscrit, int idcompte, String nom, String prenom, String adresese, String mail) {
        this.idinscrit = idinscrit;
        this.idcompte = idcompte;
        this.nom = nom;
        this.prenom = prenom;
        this.adresese = adresese;
        this.mail = mail;
    }
    public Responsable(int idinscrit, int idcompte, Integer numharpege, String nom, String prenom, String adresese, String mail, Integer tel) {
       this.idinscrit = idinscrit;
       this.idcompte = idcompte;
       this.numharpege = numharpege;
       this.nom = nom;
       this.prenom = prenom;
       this.adresese = adresese;
       this.mail = mail;
       this.tel = tel;
    }
   
    public int getIdinscrit() {
        return this.idinscrit;
    }
    
    public void setIdinscrit(int idinscrit) {
        this.idinscrit = idinscrit;
    }
    public int getIdcompte() {
        return this.idcompte;
    }
    
    public void setIdcompte(int idcompte) {
        this.idcompte = idcompte;
    }
    public Integer getNumharpege() {
        return this.numharpege;
    }
    
    public void setNumharpege(Integer numharpege) {
        this.numharpege = numharpege;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresese() {
        return this.adresese;
    }
    
    public void setAdresese(String adresese) {
        this.adresese = adresese;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }




}


