package com.rh.model.entities;
// Generated 29 mars 2013 11:16:42 by Hibernate Tools 3.2.1.GA



/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private int idcompte;
     private String login;
     private String pass;

    public Compte() {
    }

    public Compte(int idcompte, String login, String pass) {
       this.idcompte = idcompte;
       this.login = login;
       this.pass = pass;
    }
   
    public int getIdcompte() {
        return this.idcompte;
    }
    
    public void setIdcompte(int idcompte) {
        this.idcompte = idcompte;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


