package com.rh.model.entities;
// Generated 29 mars 2013 11:16:42 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HistoriqueEtudiantPoste generated by hbm2java
 */
public class HistoriqueEtudiantPoste  implements java.io.Serializable {


     private HistoriqueEtudiantPosteId id;
     private Date datedebut;
     private Date datefin;
     private int salaire;
     private String localisation;
     private String categorie;

    public HistoriqueEtudiantPoste() {
    }

    public HistoriqueEtudiantPoste(HistoriqueEtudiantPosteId id, Date datedebut, Date datefin, int salaire, String localisation, String categorie) {
       this.id = id;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.salaire = salaire;
       this.localisation = localisation;
       this.categorie = categorie;
    }
   
    public HistoriqueEtudiantPosteId getId() {
        return this.id;
    }
    
    public void setId(HistoriqueEtudiantPosteId id) {
        this.id = id;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }
    public int getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(int salaire) {
        this.salaire = salaire;
    }
    public String getLocalisation() {
        return this.localisation;
    }
    
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }




}


