package com.rh.model.entities;
// Generated 29 mars 2013 11:16:42 by Hibernate Tools 3.2.1.GA



/**
 * Poste generated by hbm2java
 */
public class Poste  implements java.io.Serializable {


     private int idposte;
     private Integer identreprise;
     private String intitule;
     private String description;
     private Double salaire;

    public Poste() {
    }

	
    public Poste(int idposte) {
        this.idposte = idposte;
    }
    public Poste(int idposte, Integer identreprise, String intitule, String description, Double salaire) {
       this.idposte = idposte;
       this.identreprise = identreprise;
       this.intitule = intitule;
       this.description = description;
       this.salaire = salaire;
    }
   
    public int getIdposte() {
        return this.idposte;
    }
    
    public void setIdposte(int idposte) {
        this.idposte = idposte;
    }
    public Integer getIdentreprise() {
        return this.identreprise;
    }
    
    public void setIdentreprise(Integer identreprise) {
        this.identreprise = identreprise;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(Double salaire) {
        this.salaire = salaire;
    }




}


