DROP TABLE APP.COMMANDEFOURNISSEUR_V2;
DROP TABLE APP.COMMANDECLIENT_V2;
DROP TABLE APP.PRODUIT_V2;
DROP TABLE APP.CLIENT_V2;

CREATE TABLE APP.COMPTE(
	idCompte 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	login 		VARCHAR(20) NOT NULL, 
	pass 		VARCHAR(8) NOT NULL,
	PRIMARY KEY(idCompte)
);

CREATE TABLE APP.ENTREPRISE(
	idEntreprise 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	idCompte		INT NOT NULL, 
	nomResponsable	INT NOT NULL,
	siteWeb			INT NOT NULL,
	nomEntreprise	INT NOT NULL,
	adresseSiege	INT NOT NULL,
	mail			INT NOT NULL,
	tel				INT NOT NULL,
	FOREIGN KEY(idCompte) REFERENCES APP.Compte(idCompte),
	PRIMARY KEY(idEntreprise)
);

CREATE TABLE APP.PROMOTION(
	idPromotion 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	annee 			DATE NOT NULL, 
	type 			VARCHAR(20) NOT NULL,
	PRIMARY KEY(idPromotion)
);

CREATE TABLE APP.POSTE(
	idPoste 		INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	idEntreprise 	DATE NOT NULL, 
	intitule		VARCHAR(20) NOT NULL,
	description		VARCHAR(20) NOT NULL,
	salaire			INT NOT NULL,
	PRIMARY KEY(idPromotion)
);

CREATE TABLE APP.HISTORIQUE_ETUDIANT_POSTE(
	idEtudiant 		INT NOT NULL,
	idPoste			INT NOT NULL, 
	dateDebut		DATE NOT NULL,
	dateFin			DATE NOT NULL,
	salaire			INT NOT NULL,
	localisation	VARCHAR(10) NOT NULL,
	categorie		VARCHAR(10) NOT NULL,
	FOREIGN KEY(idEtudiant) REFERENCES APP.Etudiant(idEtudiant),
	FOREIGN KEY(idPoste) REFERENCES APP.Poste(idPoste),
	PRIMARY KEY(idEtudiant, idPoste)
);

CREATE TABLE APP.ETUDIANT(
	idEtudiant		INTEGER(10),
	idPromotion		INTEGER(10),
	idCompte		INTEGER(10),
	nom 			VARCHAR(20)NOT NULL,
	prenom 			VARCHAR(20)NOT NULL,
	adresese 		VARCHAR(255)NOT NULL,
	mail			VARCHAR(30)NOT NULL,
	tel				INTEGER,      
PRIMARY KEY (idEtudiant)
FOREIGN KEY (idPromotion) REFERENCES APP.PROMOTION,
FOREIGN KEY (idCompte) REFERENCES APP.COMPTE
);

CREATE TABLE APP.RESPONSABLE(
idInscrit		INTEGER(10),
idCompte		INTEGER(10),
numHarpege		INTEGER(10),
nom 			VARCHAR(20)NOT NULL,
prenom 			VARCHAR(20)NOT NULL,
adresese 		VARCHAR(255)NOT NULL,
mail			VARCHAR(30)NOT NULL,
tel				INTEGER,      
PRIMARY KEY (idInscrit)
FOREIGN KEY (idCompte) REFERENCES APP.COMPTE
);

CREATE TABLE APP.MESSAGE(
idMessage					INTEGER(10),
idCompteEmmetteur			INTEGER(10),
idCompteDestinataire		INTEGER(10),
date						DATE,
message 					VARCHAR(255)NOT NULL,    
PRIMARY KEY (idMessage)
FOREIGN KEY (idCompteEmmetteur) REFERENCES APP.COMPTE
FOREIGN KEY (idCompteDestinataire) REFERENCES APP.COMPTE
);
