DROP TABLE ALUMNI.MESSAGE;
DROP TABLE ALUMNI.RESPONSABLE;
DROP TABLE ALUMNI.HISTORIQUE_ETUDIANT_POSTE;
DROP TABLE ALUMNI.ETUDIANT;
DROP TABLE ALUMNI.PROMOTION;
DROP TABLE ALUMNI.POSTE;
DROP TABLE ALUMNI.ENTREPRISE;
DROP TABLE ALUMNI.COMPTE;

CREATE TABLE ALUMNI.COMPTE(
	idCompte 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	login 		VARCHAR(20) NOT NULL, 
	pass 		VARCHAR(8) NOT NULL,
	PRIMARY KEY(idCompte)
);

CREATE TABLE ALUMNI.ENTREPRISE(
	idEntreprise 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	idCompte		INT NOT NULL, 
	nomResponsable	INT NOT NULL,
	siteWeb			INT NOT NULL,
	nomEntreprise	INT NOT NULL,
	adresseSiege	INT NOT NULL,
	mail			INT NOT NULL,
	tel				INT NOT NULL,
	FOREIGN KEY(idCompte) REFERENCES ALUMNI.COMPTE(idCompte),
	PRIMARY KEY(idEntreprise)
);

CREATE TABLE ALUMNI.PROMOTION(
	idPromotion 	INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	annee 			DATE NOT NULL, 
	type 			VARCHAR(20) NOT NULL,
	PRIMARY KEY(idPromotion)
);

CREATE TABLE ALUMNI.POSTE(
	idPoste 		INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
	idEntreprise 	INT NOT NULL, 
	intitule		VARCHAR(20) NOT NULL,
	description		VARCHAR(20) NOT NULL,
	salaire			INT NOT NULL,
	FOREIGN KEY(idEntreprise) REFERENCES ALUMNI.ENTREPRISE(idEntreprise),
	PRIMARY KEY(idPoste)
);

CREATE TABLE ALUMNI.ETUDIANT(
	idEtudiant		INT NOT NULL,
	idPromotion		INT NOT NULL,
	idCompte		INT NOT NULL,
	nom 			VARCHAR(20)NOT NULL,
	prenom 			VARCHAR(20)NOT NULL,
	adresese 		VARCHAR(255)NOT NULL,
	mail			VARCHAR(30)NOT NULL,
	tel				INTEGER,      
	FOREIGN KEY(idPromotion) REFERENCES ALUMNI.PROMOTION(idPromotion),
	FOREIGN KEY(idCompte) REFERENCES ALUMNI.COMPTE(idCompte),
	PRIMARY KEY(idEtudiant)
);

CREATE TABLE ALUMNI.HISTORIQUE_ETUDIANT_POSTE(
	idEtudiant 		INT NOT NULL,
	idPoste			INT NOT NULL, 
	dateDebut		DATE NOT NULL,
	dateFin			DATE NOT NULL,
	salaire			INT NOT NULL,
	localisation	VARCHAR(10) NOT NULL,
	categorie		VARCHAR(10) NOT NULL,
	FOREIGN KEY(idEtudiant) REFERENCES ALUMNI.Etudiant(idEtudiant),
	FOREIGN KEY(idPoste) REFERENCES ALUMNI.Poste(idPoste),
	PRIMARY KEY(idEtudiant, idPoste)
);

CREATE TABLE ALUMNI.RESPONSABLE(
	idInscrit		INT NOT NULL,
	idCompte		INT NOT NULL,
	numHarpege		INT NOT NULL,
	nom 			VARCHAR(20)NOT NULL,
	prenom 			VARCHAR(20)NOT NULL,
	adresese 		VARCHAR(255)NOT NULL,
	mail			VARCHAR(30)NOT NULL,
	tel				INT NOT NULL,      
	FOREIGN KEY(idCompte) REFERENCES ALUMNI.COMPTE(idCompte),
	PRIMARY KEY(idInscrit)
);

CREATE TABLE ALUMNI.MESSAGE(
	idMessage					INT NOT NULL,
	idCompteEmmetteur			INT NOT NULL,
	idCompteDestinataire		INT NOT NULL,
	date						DATE,
	message 					VARCHAR(255)NOT NULL,    
	FOREIGN KEY(idCompteEmmetteur) REFERENCES ALUMNI.COMPTE(idCompte),
	FOREIGN KEY(idCompteDestinataire) REFERENCES ALUMNI.COMPTE(idCompte),
	PRIMARY KEY(idMessage)
);
